### ISSUE TITLE
No longer working for Chrome

### ISSUE THREAD

**Issue by MiguelMonteiro** [EvHaus/youtube-hide-watched#18] opened 2018-02-22 20:23 UTC
Hi, love the script. It stopped working recently on the newer version of youtube (couldn't find youtube's version number).
Tested in regular youtube and in https://www.youtube.com/new (to use dark theme).
My browser:
Google Chrome is up to date
Version 64.0.3282.167 (Official Build) (64-bit)

**Comment by EvHaus** [comment] 2018-02-22 23:31
Hmm. It's working just fine for me on Chrome 64.

Do you see the little Eye icon (https://github.com/EvHaus/youtube-hide-watched/raw/master/screenshot.png) in the top?

**Comment by MiguelMonteiro** [comment] 2018-02-23 08:52
Yes, I see it, it just doesn't do anything when I click it.
Youtube's must have given me some new trial version that is not out yet for everybody.  I use to get a red bar showing the amount of video watched under the thumbnail, now I get a little box saying Seen. When this change happened it stoped working.

**Comment by EvHaus** [comment] 2018-02-23 16:35
Ah, yeah. If the red bar disappeared, the script would stop working. We use that bar to decide if the video is watched or not.

Ok.. I'll keep an eye on this and once I can reproduce, I'll issue a fix.

**Comment by Matmo10** [comment] 2018-03-31 19:11
I don't have the progress bars anymore either - now I just have an overlay that says 'WATCHED'. 

Here's the HTML (I'm using the new UI I think) - 

```html
<div id="overlays" class="style-scope ytd-thumbnail">
   <ytd-thumbnail-overlay-playback-status-renderer class="style-scope ytd-thumbnail">
      <yt-formatted-string class="style-scope ytd-thumbnail-overlay-playback-status-renderer">WATCHED</yt-formatted-string>
      <template is="dom-repeat" class="style-scope ytd-thumbnail-overlay-playback-status-renderer"></template>
   </ytd-thumbnail-overlay-playback-status-renderer>
   <ytd-thumbnail-overlay-time-status-renderer class="style-scope ytd-thumbnail" overlay-style="DEFAULT"><span class="style-scope ytd-thumbnail-overlay-time-status-renderer" aria-label="3 minutes, 38 seconds">
      3:38
      </span>
   </ytd-thumbnail-overlay-time-status-renderer>
</div>
```

So the [findWatchedElements](https://github.com/EvHaus/youtube-hide-watched/blob/master/main.js#L109) function doesn't find the watched elements for me anymore.

I just changed it to this which works for now:

```js
var findWatchedElements = function () {
    var watched = $('yt-formatted-string.ytd-thumbnail-overlay-playback-status-renderer');
     if (__DEV__) console.log(`[YT-HWV] Found ${watched.length} watched elements`);
     return watched;
};
```

**Comment by Matmo10** [comment] 2018-03-31 22:42
Ok actually, sometimes I do get the red progress bars....earlier I wasn't, now I am. YouTube is probably doing some A/B testing or something.

**Comment by ackoujens** [comment] 2018-04-15 12:57
Straight into production?! Who would actually do that?
Oh Yeah! YouTube!

On a more serious note. I also got a mention of my "watched later" userscript not working anymore.
I also depended on HTML elements on page to select upon. I'm wondering if I should gravitate more to using the actual YouTube API to prevent breakages like these.

**Comment by EvHaus** [comment] 2018-04-15 17:30
@ackoujens I'm not aware of any YouTube APIs that expose watched status information.

**Comment by dgarrett01** [comment] 2018-05-22 17:19
I can also confirm this isn't working. I'm using Chrome 64 bit, version 66.0.3359.181. I do have the progress bars at the bottom of my videos. Although, I don't see the icon showing up at the top.

In the TamperMonkey code editor, I see several warnings saying '$' is not defined.

**Comment by MiguelMonteiro** [comment] 2018-05-24 15:09
Funnily enough it's back working for me. Youtube keeps changing different stuff for different people...

**Comment by EvHaus** [comment] 2018-05-24 15:43
Yeah, they do. Unfortunately, I've yet to see any issues on any of my accounts -- so I can't implement a fix for the experiments they're doing. :( I'll keep this issue open and keep an eye out for changes. If I can find a way to reproduce it -- I'll see if there's anything I can do.

**Comment by tobbez** [comment] 2018-07-14 00:45
Turns out it used to be possible to retrieve the list of watched videos using the API, and if you skim the [API reference](https://developers.google.com/youtube/v3/docs/#PlaylistItems), you may get the impression that it's still possible.

However, if you check the [revision history](https://developers.google.com/youtube/v3/revision_history#september-15-2016), you can see that they removed this possibility on September 15, 2016:

> The channel resource's contentDetails.relatedPlaylists.watchHistory and contentDetails.relatedPlaylists.watchLater properties now contain values of HL and WL, respectively, for all channels.
>
> To be clear, these properties are only visible to an authorized user retrieving data about the user's own channel. The properties always contain the values HL and WL, even for an authorized user retrieving data about the user's own channel. Thus, the watch history and watch later playlist IDs cannot be retrieved via the API.
>
> In addition, requests to retrieve playlist details (playlists.list) or playlist items (playlistItems.list) for a channel's watch history or watch later playlist now return empty lists. This behavior is true for the new values, HL and WL, as well as for any watch history or watch later playlist IDs that your API Client may have already stored.

**Comment by EvHaus** [comment] 2019-09-16 04:25
Closing this as it's quite old. If this is still happening, feel free to leave more info.

**Closed by EvHaus** 2019-09-16 04:25 UTC
