### ISSUE TITLE
Comments are being removed

### ISSUE THREAD

**Issue by jrgutier** [EvHaus/youtube-hide-watched#22] opened 2019-01-05 03:08 UTC
Unsure why this is happening, but comments on videos are disappearing once they're loaded. No adblock running.

**Comment by jrgutier** [comment] 2019-01-05 03:10
I was able to isolate it to the following code:
        //Hide rows without videos
        $('ytd-item-section-renderer').each(function(i, item) {
            if ($(this).find('ytd-grid-video-renderer').not('.YT-HWV-WATCHED').length === 0) {
                //$(this).hide();
            }
        });

**Comment by EvHaus** [comment] 2019-01-05 06:58
Hmm. I can't reproduce. Can you give me a specific URL where this is happening?

**Comment by jrgutier** [comment] 2019-01-05 07:34
https://www.youtube.com/watch?v=XN5N1BEcwDw is where I noticed it.

**Comment by EvHaus** [comment] 2019-01-05 23:07
Hmm. Strange. I'm not seeing the issue. I'll keep an eye on this. Maybe there's a YouTube code updating rolling out that's causing this.

**Comment by EvHaus** [comment] 2019-09-16 04:25
Closing this as it's quite old. If this is still happening, feel free to leave a comment.

**Closed by EvHaus** 2019-09-16 04:25 UTC
