### ISSUE TITLE
Shorts not being dimmed or hidden anymore

### ISSUE THREAD

**Issue by vodkapmp** [EvHaus/youtube-hide-watched#248] opened 2024-09-10 15:05 UTC
I've noticed over the last week or so that shorts aren't hidden or dimmed anymore.
This goes for both the scubscriptions and recommended pages.

What can I do to help debug this? It happens on multiple machines for me, both in firefox and chrome.

**Comment by vodkapmp** [comment] 2024-09-11 14:29
The fix in #249 solves the problem.

**Comment by Goury** [comment] 2024-09-19 16:23
Affects me too

**Comment by EvHaus** [comment] 2024-09-21 23:50
I'm still not able to reproduce this as YouTube hasn't rolled out the changes for my account, but I've merged the fix in #249. Hopefully this fixes it for you guys. Released in v6.6

**Closed by EvHaus** 2024-09-21 23:50 UTC

**Comment by netjeff** [comment] 2024-09-22 16:24
It's working for me now.  Thanks!
