### ISSUE TITLE
shorts button .... New?

### ISSUE THREAD

**Issue by headcreep** [EvHaus/youtube-hide-watched#131] opened 2023-02-10 16:22 UTC
The shorts button does nothing when toggled. Greyed out or with a line through it and I'm still seeing shorts. Also, i don't ever remember seeing a shorts button when i first installed this userscript and had it worked, i would have no complaints. But seeing how it's not can't help but wish this was 2 separate scripts.

**Comment by EvHaus** [comment] 2023-02-10 21:41
Hmm. It should be working when you're on the Subscriptions page. Which YouTube page are you on?

![script](https://user-images.githubusercontent.com/226640/218204279-af2b4eae-e8a2-47af-8249-0e37f3a8d9c3.gif)

**Comment by EvHaus** [comment] 2023-06-08 05:03
Will close this. If this is still a problem, please reply back with some more details on where the issue is happening.

**Closed by EvHaus** 2023-06-08 05:03 UTC
